logging:
  level:
    root: error

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:invoice-app
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
  main:
    banner-mode: off
  security:
    user:
      name: admin@gmail.com
      password: password
